#!/usr/bin/env python3
"""Build the game-native Cangjie 5 lookup table from Rime's base dictionary.

Usage:
    python tools/build_cangjie.py \
        tools/cangjie5.base.dict.yaml \
        data/input/cangjie5.lua

The input file is Rime's cangjie5.base.dict.yaml.  Candidate order is kept
exactly as it appears in the source table; this script does not apply word
frequency, simplification, or project-specific reranking.
"""

from __future__ import annotations

import argparse
from collections import OrderedDict
from pathlib import Path


def lua_quote(text: str) -> str:
    """Return a Lua double-quoted string literal."""
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def read_rime_table(path: Path) -> OrderedDict[str, list[str]]:
    by_code: OrderedDict[str, list[str]] = OrderedDict()
    in_body = False

    for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not in_body:
            if raw.strip() == "...":
                in_body = True
            continue

        if not raw or raw.startswith("#"):
            continue

        fields = raw.split("\t")
        if len(fields) < 2:
            raise ValueError(f"{path}:{line_no}: expected TAB-separated text and code")

        text, code = fields[0], fields[1].strip().lower()
        if not code.isalpha() or len(code) > 5:
            raise ValueError(f"{path}:{line_no}: invalid Cangjie code {code!r}")

        candidates = by_code.setdefault(code, [])
        if text not in candidates:
            candidates.append(text)

    if not in_body:
        raise ValueError(f"{path}: missing Rime dictionary body marker (...)")
    return by_code


def validate_font(by_code: OrderedDict[str, list[str]], font_path: Path) -> None:
    """Fail if the selected translation font cannot render a candidate."""
    try:
        from fontTools.ttLib import TTFont
    except ImportError as exc:
        raise SystemExit("--font requires the Python fontTools package") from exc

    font = TTFont(font_path, lazy=True)
    cmap: set[int] = set()
    for subtable in font["cmap"].tables:
        cmap.update(subtable.cmap.keys())

    missing: list[str] = []
    for candidates in by_code.values():
        for ch in candidates:
            if ord(ch) not in cmap:
                missing.append(ch)
    if missing:
        preview = " ".join(missing[:20])
        raise SystemExit(
            f"{font_path}: missing {len(missing)} Cangjie candidate glyphs; first: {preview}"
        )


def write_lua(path: Path, by_code: OrderedDict[str, list[str]], source_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("-- GENERATED FILE; do not edit by hand.\n")
        out.write("-- Generated by tools/build_cangjie.py from " + source_name + ".\n")
        out.write("-- Candidate order is source-table order; no frequency reranking is applied.\n")
        out.write("-- Source table attribution: Rime rime-cangjie / cangjie5.base.dict.yaml.\n")
        out.write("-- The upstream table header identifies the table data as GPL-licensed.\n\n")
        out.write("return {\n")
        for code, candidates in by_code.items():
            joined = ", ".join(lua_quote(ch) for ch in candidates)
            out.write(f"  [{lua_quote(code)}] = {{{joined}}},\n")
        out.write("}\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--font", type=Path, help="optionally verify candidate glyph coverage")
    args = parser.parse_args()

    table = read_rime_table(args.source)
    if args.font:
        validate_font(table, args.font)
    write_lua(args.output, table, args.source.name)
    candidate_count = sum(len(v) for v in table.values())
    print(f"wrote {len(table)} codes / {candidate_count} candidates -> {args.output}")


if __name__ == "__main__":
    main()
